openapi: 3.2.0
info:
  title: Iru Endpoint Management Self Service API
  description: '# Welcome to the Iru Endpoint Management API Documentation


    **Note:** Kandji is in the process of changing to Iru.'
  version: 1.0.0
servers:
- url: https://{subdomain}.api.kandji.io
  description: US Server
  variables:
    subdomain:
      default: your-subdomain
      description: Your Iru Endpoint Management subdomain
- url: https://{subdomain}.api.eu.kandji.io
  description: EU Server
  variables:
    subdomain:
      default: your-subdomain
      description: Your Iru Endpoint Management subdomain
security:
- BearerAuth: []
tags:
- name: Self Service
paths:
  /api/v1/self-service/categories:
    get:
      summary: List Self Service Categories
      description: This endpoint retrieves a list of self-service categories and their associated IDs.
      parameters: []
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                type: object
                example:
                - id: e9010a08-a546-470b-a633-04ee27dadfb3
                  name: Apps
                - id: 1087f69d-37a3-44f6-a0d8-2b33f5a336bb
                  name: Productivity
                - id: 26a01803-f871-40b7-8c1a-6cae9983c22e
                  name: Utilities
                - id: 2f9912d1-d784-4248-905c-3834812c5537
                  name: Security
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Bad Request
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Unauthorized
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Not Found
      tags:
      - Self Service
      operationId: getApiV1SelfServiceCategories
      x-operation-id-source: derived
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
