openapi: 3.2.0
info:
  title: Iru Endpoint Management Settings API
  description: '# Welcome to the Iru Endpoint Management API Documentation


    **Note:** Kandji is in the process of changing to Iru.'
  version: 1.0.0
servers:
- url: https://{subdomain}.api.kandji.io
  description: US Server
  variables:
    subdomain:
      default: your-subdomain
      description: Your Iru Endpoint Management subdomain
- url: https://{subdomain}.api.eu.kandji.io
  description: EU Server
  variables:
    subdomain:
      default: your-subdomain
      description: Your Iru Endpoint Management subdomain
security:
- BearerAuth: []
tags:
- name: Settings
paths:
  /api/v1/settings/licensing:
    get:
      summary: Licensing
      description: This request returns Iru Endpoint Management tenant licensing and utilization information.
      parameters: []
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                type: object
                properties:
                  counts:
                    type: object
                    properties:
                      computers_count:
                        type: integer
                        example: 8
                      ios_count:
                        type: integer
                        example: 0
                      ipados_count:
                        type: integer
                        example: 1
                      macos_count:
                        type: integer
                        example: 7
                      tvos_count:
                        type: integer
                        example: 0
                  limits:
                    type: object
                    properties:
                      plan_type:
                        type: string
                        example: single_limit
                      max_devices:
                        type: integer
                        example: 10
                      max_devices_per_platform:
                        type: object
                        properties:
                          macos:
                            type: integer
                            example: 0
                          ios_ipados:
                            type: integer
                            example: 0
                  tenantOverLicenseLimit:
                    type: boolean
                    example: false
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Bad Request
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Unauthorized
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Not Found
      tags:
      - Settings
      operationId: getApiV1SettingsLicensing
      x-operation-id-source: derived
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
