openapi: 3.2.0
info:
  title: Iru Endpoint Management Tags API
  description: '# Welcome to the Iru Endpoint Management API Documentation


    **Note:** Kandji is in the process of changing to Iru.'
  version: 1.0.0
servers:
- url: https://{subdomain}.api.kandji.io
  description: US Server
  variables:
    subdomain:
      default: your-subdomain
      description: Your Iru Endpoint Management subdomain
- url: https://{subdomain}.api.eu.kandji.io
  description: EU Server
  variables:
    subdomain:
      default: your-subdomain
      description: Your Iru Endpoint Management subdomain
security:
- BearerAuth: []
tags:
- name: Tags
paths:
  /api/v1/tags:
    get:
      summary: Get Tags
      description: This request returns configured tags.
      parameters:
      - name: search
        in: query
        required: false
        description: Return resultes containing a given tag search string.
        schema:
          type: string
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                type: object
                example:
                  count: 2
                  next: null
                  previous: null
                  results:
                  - id: 71dd53f1-104e-41a2-82ca-43a375b7f63d
                    name: accuhive_01
                  - id: 4fe23c39-7a9a-435c-bab3-d2e9fd1974c6
                    name: accuhive_02
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Bad Request
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Unauthorized
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Not Found
      tags:
      - Tags
      operationId: getApiV1Tags
      x-operation-id-source: derived
    post:
      summary: Create Tag
      description: This request creates a tag.
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: The name of the tag to create.
              required:
              - name
            example:
              name: accuhive_01
      responses:
        '201':
          description: success
          content:
            application/json:
              schema:
                type: object
                example:
                  id: 1467cc35-39e3-435d-8816-34c849c15bc3
                  name: accuhive_01
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Bad Request
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Unauthorized
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Not Found
      tags:
      - Tags
      operationId: postApiV1Tags
      x-operation-id-source: derived
  /api/v1/tags/{tag_id}:
    patch:
      summary: Update Tag
      description: This request updates a tag name.
      parameters:
      - name: tag_id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                type: object
                example:
                  id: 4fe23c39-7a9a-435c-bab3-d2e9fd1974c6
                  name: accuhive_02
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Bad Request
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Unauthorized
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Not Found
      requestBody:
        required: true
        description: JSON payload containing the tag update information
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: The new name for the tag
                  example: accuhive_02
              required:
              - name
      tags:
      - Tags
      operationId: patchApiV1TagsByTagId
      x-operation-id-source: derived
    delete:
      summary: Delete Tag
      description: This request deletes a tag.
      parameters:
      - name: tag_id
        in: path
        required: true
        schema:
          type: string
      responses:
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Bad Request
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Unauthorized
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Not Found
      tags:
      - Tags
      operationId: deleteApiV1TagsByTagId
      x-operation-id-source: derived
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
